language: node_js
node_js:
  - '6'
git:
  depth: 5
script:
  - npm run check:src
  - npm run build
after_success:
  - npm run test:coverage
  - npm run test:report
branches:
  only:
    - master
cache:
  directories:
    - node_modules